# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Checkout project
        uses: actions/checkout@v4
    
      - name: Install token-transformer
        run: npm install token-transformer
        working-directory: Sources/Token-Translation/
      
      - name: Run token-transformer
        run: npx token-transformer tokens/design-tokens.json tokens/transformed-tokens.json
        working-directory: Sources/Token-Translation/

      - name: Install style-dictionary
        run: npm install -D style-dictionary
        working-directory: Sources/Token-Translation/

      - name: Run style-dictionary
        run: npx style-dictionary build
        working-directory: Sources/Token-Translation/

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "public static let tokenSetOrder0 = core"
          replace: " "
          include: "Sources/**"
          regex: false
          
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "public static let tokenSetOrder1 = light"
          replace: " "
          include: "Sources/**"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "public static let tokenSetOrder2 = theme"
          replace: " "
          include: "Sources/**"
          regex: false

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "public enum {"
          replace: "public enum StyleDictionaryEnum {"
          include: "Sources/**"
          regex: false
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
